from typing import Protocol


class VCSAdapter(Protocol):
    def create_branch(self, branch_name: str, base_branch: str) -> None: ...
    def push_commits(self, branch: str, changed_files: list[str], message: str) -> None: ...
    def checkout_branch(self, branch_name: str) -> None: ...
    def create_pr(self, title: str, body: str, head_branch: str, base_branch: str) -> str: ...
    def merge_pr(self, pr_id: str) -> None: ...
    def add_pr_comment(self, pr_id: str, body: str) -> None: ...
    def create_project_pr(self, head_branch: str, base_branch: str, title: str, body: str) -> str: ...
    def is_pr_merged(self, pr_id: str) -> bool: ...
    def list_task_branches(self, prefix: str) -> list[str]: ...
    def find_pr_for_branch(self, branch_name: str) -> tuple[str, bool] | None: ...
    def delete_branch(self, branch_name: str) -> None: ...
    def ensure_branch(self, branch_name: str, base_branch: str) -> None: ...
    def branch_has_new_commits(self, base_branch: str, head_branch: str) -> bool: ...
