from datetime import datetime
from typing import Any, Protocol

from haive.models.enums import TaskStatus
from haive.models.task import Project, Task, TaskComment


class PMAdapter(Protocol):
    def get_project(self, project_id: str) -> Project: ...
    def get_tasks(self, project_id: str) -> list[Task]: ...
    def read_new_comments(self, project_id: str, since: datetime) -> list[TaskComment]: ...
    # Write methods — implemented in Step 6:
    def create_task(self, project_id: str, task: Any) -> Task: ...
    def set_dependency(self, task_id: str, depends_on: list[str]) -> None: ...
    def update_status(self, task_id: str, status: TaskStatus) -> None: ...
    def add_comment(self, task_id: str, body: str) -> None: ...
